---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Протокол HTTPS
  - Поле фильтра поиска по цене должно показывать стоимость самого дорогого товара на сайте в той валюте, которая установлена
  - Пользователь не должен иметь возможности редактировать, удалять и добавлять новые товары в магазин
  - У пользователя не должно быть доступа к чужим корзинам
  - В фильтр товаров по цене нельзя вписать отрицательное значение
